# Generated by Django 4.2.6 on 2023-10-26 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('Payme,', 'Paymedan'), ('Click', 'Clickdan'), ('Uzum', 'Uzumdan'), ('Cash', 'Naqd pul')], default='CARD', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customer.customer')),
                ('product', models.ManyToManyField(blank=True, related_name='Product', to='product.product')),
            ],
        ),
    ]
